from datetime import datetime
from airflow import DAG
from airflow.operators.python import PythonOperator
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import requests
import json

# Email configuration - Brevo (Real emails)
SMTP_HOST = "smtp-relay.brevo.com"
SMTP_PORT = 587
SMTP_LOGIN = ""  # Brevo SMTP login (for authentication)
SMTP_PASSWORD = ""  # Brevo SMTP key
SENDER_EMAIL = ""  # Must be verified in Brevo (used in "From" field)
RECIPIENT_EMAIL = ""  # Real recipient email


# Stock service configuration
STOCK_SERVICE_URL = "http://stock-service:8000/stocks"

def fetch_stock_analysis():
    """
    Fetch stock analysis from the stock service.
    Returns the analysis text or error message.
    """
    try:
        print(f"Fetching stock analysis from {STOCK_SERVICE_URL}...")
        response = requests.get(STOCK_SERVICE_URL, timeout=30)
        response.raise_for_status()

        data = response.json()
        print(f"Successfully fetched stock data for {len(data.get('stocks', []))} stocks")

        # Return the analysis text
        return data.get('analysis', 'No analysis available')

    except requests.exceptions.RequestException as e:
        error_msg = f"Failed to fetch stock analysis: {str(e)}"
        print(error_msg)
        return error_msg
    except Exception as e:
        error_msg = f"Unexpected error: {str(e)}"
        print(error_msg)
        return error_msg

def send_stock_email(**context):
    """
    Send stock analysis email using Brevo SMTP.
    Fetches the analysis from the previous task.
    """
    # Get the stock analysis from XCom (passed from previous task)
    ti = context['ti']
    stock_analysis = ti.xcom_pull(task_ids='fetch_stock_analysis')

    if not stock_analysis:
        stock_analysis = "No stock analysis available"

    try:
        # Create message
        message = MIMEMultipart()
        message["From"] = SENDER_EMAIL
        message["To"] = RECIPIENT_EMAIL
        message["Subject"] = f"Daily Stock Analysis - {datetime.now().strftime('%Y-%m-%d')}"

        # Email body with stock analysis
        body = f"""
Hello!

Here is your daily stock analysis for TSLA, PLTR, and GOOGL:

{stock_analysis}

---
This email was automatically generated by your Airflow DAG.
        """
        message.attach(MIMEText(body, "plain"))

        # Connect to Brevo SMTP server
        print(f"Connecting to {SMTP_HOST}:{SMTP_PORT}...")
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
        server.starttls()  # Enable TLS encryption

        # Login with Brevo credentials (SMTP login + SMTP key)
        print(f"Logging in to Brevo with {SMTP_LOGIN}...")
        server.login(SMTP_LOGIN, SMTP_PASSWORD)

        # Send email
        print(f"Sending stock analysis email to {RECIPIENT_EMAIL}...")
        server.send_message(message)

        # Close connection
        server.quit()
        print("Stock analysis email sent successfully!")

    except Exception as e:
        error_msg = f"Failed to send email: {str(e)}"
        print(error_msg)
        raise

with DAG(
    dag_id="stock_analysis_email_dag",
    start_date=datetime(2023, 1, 1),
    schedule_interval="0 9 * * 1-5",  # Run at 9 AM on weekdays (Mon-Fri)
    catchup=False,
    description="Fetch stock analysis from service and send via email",
    tags=['stocks', 'email', 'daily']
) as dag:

    # Task 1: Fetch stock analysis from the service
    fetch_task = PythonOperator(
        task_id="fetch_stock_analysis",
        python_callable=fetch_stock_analysis
    )

    # Task 2: Send the analysis via email
    email_task = PythonOperator(
        task_id="send_stock_email",
        python_callable=send_stock_email,
        provide_context=True
    )

    # Define task dependencies
    fetch_task >> email_task
