apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://hadoop-namenode:9000</value>
      </property>
    </configuration>
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>dfs.replication</name>
        <value>2</value>
      </property>
      <property>
        <name>dfs.namenode.name.dir</name>
        <value>/tmp/hadoop/dfs/name</value>
      </property>
    </configuration>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
  labels:
    app: hadoop
    component: namenode
spec:
  selector:
    matchLabels:
      app: hadoop
      component: namenode
  replicas: 1
  template:
    metadata:
      labels:
        app: hadoop
        component: namenode
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: namenode
        image: apache/hadoop:3
        ports:
        - containerPort: 9000
          name: fs
        - containerPort: 9870
          name: web
        env:
        - name: HADOOP_HOME
          value: "/opt/hadoop"
        command:
        - "/bin/bash"
        - "-c"
        - |
          mkdir -p /tmp/hadoop/dfs/name
          $HADOOP_HOME/bin/hdfs namenode -format -force
          $HADOOP_HOME/bin/hdfs --config /opt/hadoop/etc/hadoop namenode
        volumeMounts:
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
        - name: hadoop-data
          mountPath: /tmp/hadoop
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-config
      - name: hadoop-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  labels:
    app: hadoop
    component: namenode
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    name: fs
  - port: 9870
    targetPort: 9870
    name: web
  selector:
    app: hadoop
    component: namenode 