apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  selector:
    matchLabels:
      app: spark
      component: worker
  replicas: 2
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:3.4.1
        ports:
        - containerPort: 8081
          name: web
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        - name: SPARK_WORKER_PORT
          value: "38000"
        - name: SPARK_LOCAL_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    name: web
  selector:
    app: spark
    component: worker 