apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
data:
  spark-defaults.conf: |
    spark.master                     spark://spark-master:7077
    spark.hadoop.fs.defaultFS       hdfs://hadoop-namenode:9000
  spark-env.sh: |
    #!/bin/bash
    export SPARK_MASTER_PORT=7077
    export SPARK_MASTER_WEBUI_PORT=8080
    export SPARK_WORKER_WEBUI_PORT=8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
    component: master
spec:
  selector:
    matchLabels:
      app: spark
      component: master
  replicas: 1
  template:
    metadata:
      labels:
        app: spark
        component: master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.4.1
        ports:
        - containerPort: 7077
          name: spark
        - containerPort: 8080
          name: web
        env:
        - name: SPARK_MODE
          value: "master"
        volumeMounts:
        - name: spark-config
          mountPath: /opt/bitnami/spark/conf/spark-defaults.conf
          subPath: spark-defaults.conf
        - name: spark-config
          mountPath: /opt/bitnami/spark/conf/spark-env.sh
          subPath: spark-env.sh
      volumes:
      - name: spark-config
        configMap:
          name: spark-config
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark
    component: master
spec:
  type: LoadBalancer
  ports:
  - port: 7077
    targetPort: 7077
    name: spark
  - port: 8080
    targetPort: 8080
    name: web
  selector:
    app: spark
    component: master 