# insert 10 random records into the users table

INSERT INTO users (id, name, created_at)
SELECT 
  FLOOR(RAND() * 1000000) AS id,
  CONCAT('User_', FLOOR(RAND() * 10000)) AS name,
  NOW() AS created_at
FROM
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 
   UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS tmp;