# ---------------------------
# Kafka UI Instance 1
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-1
  labels:
    app: kafka-ui-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-1
  template:
    metadata:
      labels:
        app: kafka-ui-1
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka-1"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-1-service
spec:
  selector:
    app: kafka-ui-1
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort

---
# ---------------------------
# Kafka UI Instance 2
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-2
  labels:
    app: kafka-ui-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-2
  template:
    metadata:
      labels:
        app: kafka-ui-2
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka-2"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-2-service
spec:
  selector:
    app: kafka-ui-2
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort