# ---------------------------
# Kafka UI Instance 1 (Primary)
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-primary
  labels:
    app: kafka-ui-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-primary
  template:
    metadata:
      labels:
        app: kafka-ui-primary
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "my-kafka-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-primary-service
spec:
  selector:
    app: kafka-ui-primary
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort

---
# ---------------------------
# Kafka UI Instance 2 (Secondary)
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-secondary
  labels:
    app: kafka-ui-secondary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-secondary
  template:
    metadata:
      labels:
        app: kafka-ui-secondary
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "my-kafka-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-secondary-service
spec:
  selector:
    app: kafka-ui-secondary
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort